site_name: Amazon EKS Blueprints for Terraform
repo_name: "aws-ia/terraform-aws-eks-blueprints"
repo_url: "https://github.com/aws-ia/terraform-aws-eks-blueprints"
edit_uri: "edit/main/docs/"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - awesome-pages
  - include-markdown
extra:
  version:
    provider: mike
