apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pega-ecr-username
  namespace: pega-web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pega-ecr-username
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: pega-ecr-credentials-v2 #AWS Secrets Manager secret name
      property: username #AWS Secrets Manager secret key

 