apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pega-credentials-secret2
  namespace: pega-web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pega-credentials-secret2
    creationPolicy: Owner
    template:
      type: kubernetes.io
      engineVersion: v2
      data:
        DB_PASSWORD: "\"{{ .DB_PASSWORD }}\""
        DB_USERNAME: "{{ .DB_USERNAME }}"
        CASSANDRA_USERNAME : "{{ .CASSANDRA_USERNAME }}" 
        CASSANDRA_PASSWORD : "{{ .CASSANDRA_PASSWORD }}" 
        HZ_CS_AUTH_USERNAME: "{{ .HZ_CS_AUTH_USERNAME }}"  
        HZ_CS_AUTH_PASSWORD: "{{ .HZ_CS_AUTH_PASSWORD }}"
  data:
  - secretKey: CASSANDRA_USERNAME
    remoteRef:
      key: pega-cassandra-v2 #AWS Secrets Manager secret name
      property: CASSANDRA_USERNAME #AWS Secrets Manager secret key
  
  - secretKey: CASSANDRA_PASSWORD
    remoteRef:
      key: pega-cassandra-v2 #AWS Secrets Manager secret name
      property: CASSANDRA_PASSWORD #AWS Secrets Manager secret key
  
  - secretKey: HZ_CS_AUTH_USERNAME
    remoteRef:
      key: pega-hzcast-v2 #AWS Secrets Manager secret name
      property: HZ_CS_AUTH_USERNAME #AWS Secrets Manager secret key
  
  - secretKey: HZ_CS_AUTH_PASSWORD
    remoteRef:
      key: pega-hzcast-v2 #AWS Secrets Manager secret name
      property: HZ_CS_AUTH_PASSWORD #AWS Secrets Manager secret key
        
  - secretKey: DB_USERNAME
    remoteRef: 
      key: rds!cluster-87263d3e-1fc0-40d7-9e17-81123c3ccf63 #AWS Secrets Manager secret name
      property: username #AWS Secrets Manager secret key
  - secretKey: DB_PASSWORD
    remoteRef: 
      key: rds!cluster-87263d3e-1fc0-40d7-9e17-81123c3ccf63 #AWS Secrets Manager secret name
      property: password #AWS Secrets Manager secret key
