apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: pega-web-sa
  namespace : pega-web
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::136658121779:role/pega-secrets-role # ARN of pega-secrets-role