apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: pega-web
spec:
  serviceAccountName: pega-web-sa
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /opt/pega/secrets
      name: pega-volume-credentials
    - mountPath: /opt/pega/registry-secrets
      name: pega-registry-secret
    - mountPath: /opt/pega/dbConnection
      name: postgresql-connection-details  
  volumes:  
  - name: pega-volume-credentials
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "pega-credentials-secret"
  - name: postgresql-connection-details
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
          secretProviderClass: "postgresql-connection-details"
  - name: pega-registry-secret
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
          secretProviderClass: "pega-ecr-credentials"                