apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pega-ecr-credentials
  namespace: pega-web
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "pega-ecr-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: url 
            objectAlias: url 
          - path: username
            objectAlias: username
          - path: password 
            objectAlias: password
          
       


