apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pega-credentials-secret
  namespace: pega-web
spec:
  provider: aws
  parameters: 
    objects: | 
      - objectName: "rds!cluster-d14866d8-18df-4076-b0a9-ff905e6bf12b"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: DB_USERNAME
          - path: password
            objectAlias: DB_PASSWORD
      - objectName: "pega-cassandra"
        objectType: "secretsmanager"
        jmesPath:
          - path: CASSANDRA_USERNAME
            objectAlias: CASSANDRA_USERNAME
          - path: CASSANDRA_PASSWORD
            objectAlias: CASSANDRA_PASSWORD
      - objectName: "pega-hzcast"
        objectType: "secretsmanager"
        jmesPath:
          - path: HZ_CS_AUTH_USERNAME
            objectAlias: HZ_CS_AUTH_USERNAME
          - path: HZ_CS_AUTH_PASSWORD
            objectAlias: HZ_CS_AUTH_PASSWORD
                   



