apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pega-ecr-password
  namespace: pega-web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pega-ecr-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: pega-ecr-credentials-v2 #AWS Secrets Manager secret name
      property: password #AWS Secrets Manager secret key
  
 