apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pega-credentials-secret
  namespace: pega-web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pega-credentials-secret
    creationPolicy: Owner
  data:
  - secretKey: CASSANDRA_USERNAME
    remoteRef:
      key: pega-cassandra-v2 #AWS Secrets Manager secret name
      property: CASSANDRA_USERNAME #AWS Secrets Manager secret key
  
  - secretKey: CASSANDRA_PASSWORD
    remoteRef:
      key: pega-cassandra-v2 #AWS Secrets Manager secret name
      property: CASSANDRA_PASSWORD #AWS Secrets Manager secret key
  
  - secretKey: HZ_CS_AUTH_USERNAME
    remoteRef:
      key: pega-hzcast-v2 #AWS Secrets Manager secret name
      property: HZ_CS_AUTH_USERNAME #AWS Secrets Manager secret key
  
  - secretKey: HZ_CS_AUTH_PASSWORD
    remoteRef:
      key: pega-hzcast-v2 #AWS Secrets Manager secret name
      property: HZ_CS_AUTH_PASSWORD #AWS Secrets Manager secret key
  
  - secretKey: DB_USERNAME
    remoteRef: 
      key: rds!cluster-2571d018-7087-402f-997a-7a6c79abc06d #AWS Secrets Manager secret name
      property: username #AWS Secrets Manager secret key
  - secretKey: DB_PASSWORD
    remoteRef: 
      key: rds!cluster-2571d018-7087-402f-997a-7a6c79abc06d #AWS Secrets Manager secret name
      property: password #AWS Secrets Manager secret key
